In [24]:
import numpy as np

In [25]:
x = np.array(12)

In [26]:
x

array(12)

In [27]:
print(x)

12


In [28]:
x.ndim

0

In [29]:
x = np.array([12, 3, 6, 14, 7])

In [30]:
x

array([12,  3,  6, 14,  7])

In [31]:
x.ndim

1

In [32]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1]])

In [33]:
x.ndim

2

In [34]:
x.shape

(2, 5)

In [35]:
from keras.datasets import mnist

In [36]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [37]:
print(train_images.ndim)

3


In [38]:
print(train_images.shape)

(60000, 28, 28)


In [39]:
print(train_images.dtype)

uint8


In [56]:
x = np.random.randint(100000, size=(1,10000000))

In [57]:
y = np.random.randint(10000, size= (1, 10000000))

In [53]:
x.dtype

dtype('int32')

In [54]:
x

array([[51836, 38005, 42271, ..., 76071, 23716,  1536]])

In [55]:
np.dot(x, y.T)

array([[1809476486]])

In [69]:
np.dot(x, y.T)

array([[-111849211]])